SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCOTACAO;
CREATE DATABASE DBCOTACAO;
USE DBCOTACAO;

CREATE TABLE COTACAO (
	IDCOTACAO INT NOT NULL AUTO_INCREMENT
    , DTCOTACAO DATE
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY (IDCOTACAO)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY(IDPRODUTO)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL AUTO_INCREMENT
    , IDPRODUTO INT NOT NULL
    , DTVENDA DATE
    , VALOR_REAL NUMERIC(8,2)
    , VALOR_DOLAR NUMERIC(8,2)
    , PRIMARY KEY (IDVENDA)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
    );


INSERT INTO PRODUTO (NOME, VALOR)VALUES('CELULAR', 200);
INSERT INTO PRODUTO (NOME, VALOR)VALUES('TABLET', 350);

INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -5 DAY)), 4.09 - 0.55);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -4 DAY)), 4.09 - 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -3 DAY)), 4.09 - 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -2 DAY)), 4.09 - 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -1 DAY)), 4.09 - 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  0 DAY)), 4.09 - 0.05);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  1 DAY)), 4.09 + 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  2 DAY)), 4.09 + 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  3 DAY)), 4.09 + 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  4 DAY)), 4.09 + 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  5 DAY)), 4.09 + 0.55);


/*
QUESTÃO:
1. SÓ PODE INCLUIR VENDA, SE TIVER COTAÇÃO PARA A DATA DA VENDA

2. QUANDO UM PRODUTO FOR INCLUÍDO OU ALTERADO O VALOR DO PRODUTO 
EM DÓLAR CALCULADO COM BASE NA COTAÇÃO, PARA LOCALIZAR A COTAÇÃO COMPARE A DATA DE VENDA COM A DATA DA COTACAO;
*/


DELIMITER $$
CREATE TRIGGER TR_BI_VENDA BEFORE INSERT ON VENDA FOR EACH ROW
	BEGIN
	IF(NEW.DTVENDA NOT IN (SELECT COTACAO.DTCOTACAO FROM COTACAO)) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NÃO HÁ COTAÇÃO PARA ESSA DATA';
	ELSE 
		SET NEW.VALOR_REAL = (SELECT VALOR FROM PRODUTO WHERE IDPRODUTO = NEW.IDPRODUTO),NEW.VALOR_DOLAR=NEW.VALOR_REAL/(SELECT COTACAO.VALOR FROM COTACAO WHERE DTCOTACAO = CURRENT_DATE());
    END IF;
    END $$
CREATE TRIGGER TR_AU_PRODUTO BEFORE UPDATE ON PRODUTO FOR EACH ROW
BEGIN
	UPDATE VENDA SET VALOR_REAL = NEW.VALOR,VALOR_DOLAR=NEW.VALOR/(SELECT COTACAO.VALOR FROM COTACAO WHERE DTCOTACAO = (SELECT DTVENDA FROM VENDA WHERE IDPRODUTO = NEW.IDPRODUTO));
END $$


DELIMITER ;
INSERT INTO PRODUTO VALUES(default,'monitor', 200);
INSERT INTO VENDA VALUES(DEFAULT,3, NOW(),3.23,6.23);
update produto set valor = 20 where idproduto = 3;
SELECT * FROM PRODUTO;
SELECT * FROM VENDA;
SELECT * FROM COTACAO;


